[project]
name = "coc-elt"
version = "0.1.0"
description = "Clash of Clans ELT pipeline on Google Cloud Platform"
readme = "README.md"
authors = [
    { name = "Jose Chavez", email = "josechavezuriarte@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "requests>=2.31.0",
    "pydantic>=2.5.0",
    "pydantic-settings>=2.1.0",
    "google-cloud-bigquery>=3.13.0",
    "pymongo>=4.17.0",
]

[dependency-groups]
dev = [
    "diagrams>=0.25.1",
    "ipython>=9.15.0",
    "pytest>=7.4.0",
    "pytest-cov>=4.1.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
